apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mbu2j3jc1-dotnet-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mbu2j3jc1-dotnet-basic 
  name: mbu2j3jc1-dotnet-basic
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mbu2j3jc1-dotnet-basic 
